/* author: Raimondas */
/* creation date: 2002.05.06 */
/* title: zodyno duomenu baze */

//Duomenu baze
var MaxValue=115;
Angl = new Array(MaxValue); 
Liet = new Array(MaxValue);

//Reikalingos dalys
function ATD(Vieta,Angliskai,Lietuviskai){
 Angl[Vieta] = Angliskai;
 Liet[Vieta] = Lietuviskai;
 }

//Pridedami elementai i zodyna
 ATD(0,"File","Failas");
 ATD(1,"Edit","Redagavimas");
 ATD(2,"View","Vaizdas");
 ATD(3,"Configure","Konfiguruoti");
 ATD(4,"Insert","Áterpti");
 ATD(5,"Save As","Áraðyti Taip");
 ATD(6,"Save","Áraðyti");
 ATD(7,"Print","Spausdinti");
 ATD(8,"Modify","Modifikuoti");
 ATD(9,"Customize","Derinti");
 ATD(10,"Screen","Ekranas");
 ATD(11,"Desktop","Darbastalis");
 ATD(12,"Trial","Bandomoji");
 ATD(13,"Version","Versija");
 ATD(14,"Free","Nemokama");
 ATD(15,"Shareware","Bandomoji");
 ATD(16,"Left","Kairë");
 ATD(17,"Right","Deðinë");
 ATD(18,"Text","Tekstas");
 ATD(19,"Search","Ieðkoti");
 ATD(20,"Find","Rasti");
 ATD(21,"Replace","Pakeisti");
 ATD(22,"Change","Pakeisti");
 ATD(23,"Yes","Taip");
 ATD(24,"No","Ne");
 ATD(25,"Yes To All","Taip Visiems");
 ATD(26,"No To All","Ne Visiems");
 ATD(27,"Commands","Komandos");
 ATD(28,"Dictionary","Þodynas");
 ATD(29,"Explorer","Tyrinëtojas");
 ATD(30,"Explore","Tyrinëti");
 ATD(31,"Plug-In","Priedas");
 ATD(32,"Window","Langas");
 ATD(33,"Script","Skriptas");
 ATD(34,"Visual","Vaizdo");
 ATD(35,"Game","Þaidimas");
 ATD(36,"Player","Grotuvas");
 ATD(37,"Quit","Iðeiti");
 ATD(38,"Exit","Iðeiti");
 ATD(39,"Format","Formuot");
 ATD(40,"Format","Suformatuoti");
 ATD(41,"View","Þiûrëti");
 ATD(42,"View","Rodyti");
 ATD(43,"Search","Ieðkojimas");
 ATD(44,"Visual","Vaizdinë");
 ATD(45,"Visual","Vizualinë");
 ATD(44,"Visual","Vaizdinë");
 ATD(45,"Page","Puslapis");
 ATD(46,"Page Setup","Puslapio Nustatymai");
 ATD(47,"Floppy","Diskelis");
 ATD(48,"Error","Klaida");
 ATD(49,"Undo","Atðaukti");
 ATD(50,"Redo","Pakartoti");
 ATD(51,"Cut","Iðkirpti");
 ATD(52,"Delete","Iðtrinti");
 ATD(53,"Copy","Nukopijuoti");
 ATD(54,"Copy","Kopijuoti");
 ATD(55,"Paste","Áterpti");
 ATD(56,"Next","Kitas");
 ATD(57,"Select All","Paþymëti Viskà");
 ATD(58,"Go To","Eiti á");
 ATD(59,"Time","Laikas");
 ATD(60,"Date","Data");
 ATD(61,"Word Wrap","Þodþiø këlimas");
 ATD(62,"Font","Ðriftas");
 ATD(63,"Color","Spalva");
 ATD(64,"Name","Vardas");
 ATD(65,"Name","Pavadinimas");
 ATD(66,"Address","Adresas");
 ATD(67,"Sample","Pavyzdys");
 ATD(68,"Size","Dydis");
 ATD(66,"Style","Stilius");
 ATD(67,"Underline","Pabrauktas");
 ATD(68,"Italic","Pasviræs");
 ATD(69,"Bold","Paryðkintas");
 ATD(70,"Status Bar","Statuso eilutë");
 ATD(71,"Help","Pagalba");
 ATD(72,"About","Apie");
 ATD(73,"Always on top","Visada virðuje");
 ATD(74,"On Top","Virðuje");
 ATD(75,"History","Istorija");
 ATD(76,"Tools","Árankiai");
 ATD(78,"Menu","Meniu");
 ATD(79,"Back","Atgal");
 ATD(80,"Foward","Á prieká");
 ATD(81,"Folder","Katalogas");
 ATD(82,"Directory","Katalogas");
 ATD(83,"Locate","Vieta");
 ATD(84,"Up","Aukðtyn");
 ATD(85,"Up","Á virðø");
 ATD(86,"Down","Þemyn");
 ATD(87,"Info","Informacija");
 ATD(88,"Start","Startas");
 ATD(89,"Day","Diena");
 ATD(90,"Get","Paimti");
 ATD(91,"Put","Padëti");
 ATD(92,"Abort","Nutraukti");
 ATD(93,"Cancel","Atðaukti");
 ATD(94,"Open with","Atidaryti su");
 ATD(95,"With","Su");
 ATD(96,"Send To","Nusiøsti á");
 ATD(97,"Properties","Savybës");
 ATD(98,"Close","Uþdaryti");
 ATD(99,"Insert Disk","Ádëti diskà");
 ATD(100,"Create Shortcut","Sukurti nuorodà");
 ATD(101,"Rename","Pervadinti");
 ATD(102,"Invert Selection","Invertuoti paþymëjimà");
 ATD(103,"Selection","Paþymëjimas");
 ATD(104,"Refresh","Atnaujinti");
 ATD(105,"Internet","Internetas");
 ATD(106,"Chat","Pokalbiai");
 ATD(107,"Real","Tikras");
 ATD(108,"Real","Tikra");
 ATD(109,"Clock","Laikrodis");
 ATD(110,"My","Mano");
 ATD(111,"Music","Muzika");
 ATD(112,"Documents","Documentai");
 ATD(113,"What is this?","Kas èia yra?");
 ATD(114,"Preview","Perþiûra");